### ISSUE TITLE
Suggestion for the Used by many carousel

### ISSUE THREAD

**Issue by umaar** [kylesome/nameko-site#4]
When all the items are already displayed:

![image](https://user-images.githubusercontent.com/381495/40831662-a5b28cb8-659a-11e8-8cbf-0a851d71d561.png)

Could hide the arrows if possible

**Comment by kylesome** [comment]
Thanks for having a look @umaar ! I think this is due to me leaving some images in there while I was testing the slider, I only had 3 so I just copied them to see how the arrows looked. Will be fixed once the content is finalised 🙂

**Comment by kylesome** [comment]
Fixed with new images in https://github.com/kylesome/nameko-site/pull/6
